spring:
  application:
    name: "hexa"
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal

client:
  address:
    url: http://localhost:3001/addresses

